#!/usr/bin/env node
/**
 * Safe handoff packer: write a compact report, sync generated artifacts, run
 * the handoff check profile, zip the project, and write SHA256.
 */
import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const ROOT_DIR = path.resolve(path.dirname(__filename), '..');
const PROJECT_DIR_NAME = path.basename(ROOT_DIR);
const NPM = process.platform === 'win32' ? 'npm.cmd' : 'npm';

function parseArgs(argv = process.argv.slice(2)) {
  const args = { check: true, sync: true };
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === '--no-check') args.check = false;
    else if (token === '--no-sync') args.sync = false;
    else if (token === '--name') {
      args.name = argv[i + 1];
      i += 1;
    } else if (token.startsWith('--name=')) args.name = token.slice('--name='.length);
  }
  return args;
}

function run(command, args, cwd = ROOT_DIR) {
  const printable = [command, ...args].join(' ');
  console.log(`\n$ ${printable}`);
  const result = spawnSync(command, args, { cwd, stdio: 'inherit', env: process.env });
  if (result.status !== 0) {
    console.error(`❌ failed: ${printable}`);
    process.exit(result.status ?? 1);
  }
}

function capture(command, args, cwd = ROOT_DIR) {
  const result = spawnSync(command, args, { cwd, encoding: 'utf8' });
  if (result.status !== 0) return '';
  return result.stdout.trim();
}

function sha256(file) {
  return crypto.createHash('sha256').update(readFileSync(file)).digest('hex');
}

function timestamp() {
  return new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
}

function readProjectSummary() {
  const mapPath = path.join(ROOT_DIR, 'data', 'project-map.generated.json');
  if (!existsSync(mapPath)) return '- Project map unavailable\n';
  const projectMap = JSON.parse(readFileSync(mapPath, 'utf8'));
  return `- Pages: ${projectMap.summary.pages}\n- Clusters: ${projectMap.summary.clusters}\n- Direct landing pages: ${projectMap.summary.directLandingPages}\n`;
}

const args = parseArgs();
const stamp = timestamp();
const baseName = args.name || `mospochin-ai-navigation-pack-${stamp}`;
const parentDir = path.dirname(ROOT_DIR);
const zipPath = path.join(parentDir, `${baseName}.zip`);
const shaPath = `${zipPath}.sha256`;
const reportName = `HANDOFF_REPORT_${stamp}.md`;
const reportDir = path.join(ROOT_DIR, 'reports', 'handoff');
mkdirSync(reportDir, { recursive: true });
const reportPath = path.join(reportDir, reportName);
const gitFiles = capture('git', ['status', '--short']);

const report = `# Handoff report — ${stamp}\n\n` +
  `Generated by: \`tools/handoff-pack.mjs\`\n\n` +
  `## Package\n\n` +
  `- ZIP: \`${path.basename(zipPath)}\`\n` +
  `- SHA256: generated next to ZIP\n\n` +
  `## Commands\n\n` +
  `- sync: ${args.sync ? '`npm run sync:generated`' : 'skipped'}\n` +
  `- checks: ${args.check ? '`npm run check:handoff`' : 'skipped'}\n\n` +
  `## Project summary before final sync\n\n` +
  readProjectSummary() +
  `\n## Git status snapshot before final sync\n\n` +
  '```text\n' +
  (gitFiles || 'No git metadata/status available in this package.') +
  '\n```\n\n' +
  `## Manual reminders\n\n` +
  `- Run \`npm run check:full\` before production after image/layout/visual changes.\n` +
  `- Verify live forms, Telegram delivery, phone and WhatsApp after deploy.\n`;
writeFileSync(reportPath, report);
console.log(`✅ reports/handoff/${reportName} создан`);

// Sync after report creation so AI index/digest/deploy manifest can include it without polluting the project root.
if (args.sync) run(NPM, ['run', 'sync:generated']);
if (args.check) run(NPM, ['run', 'check:handoff']);
run(NPM, ['run', 'ai:change-manifest']);

if (existsSync(zipPath)) run('rm', ['-f', zipPath]);
if (existsSync(shaPath)) run('rm', ['-f', shaPath]);

run('zip', [
  '-qr',
  zipPath,
  PROJECT_DIR_NAME,
  '-x',
  `${PROJECT_DIR_NAME}/.git/*`,
  `${PROJECT_DIR_NAME}/node_modules/*`,
  `${PROJECT_DIR_NAME}/.cache/*`,
  `${PROJECT_DIR_NAME}/.artifacts/*`,
  `${PROJECT_DIR_NAME}/.playwright-browsers/*`,
  `${PROJECT_DIR_NAME}/build/*`,
  `${PROJECT_DIR_NAME}/reports/visual-*/*`,
  `${PROJECT_DIR_NAME}/reports/visual-audit/*`,
  `${PROJECT_DIR_NAME}/**/__pycache__/*`,
  `${PROJECT_DIR_NAME}/**/*.zip`,
  `${PROJECT_DIR_NAME}/.DS_Store`,
], parentDir);

const hash = sha256(zipPath);
writeFileSync(shaPath, `${hash}  ${path.basename(zipPath)}\n`);
console.log(`\n✅ Handoff package ready: ${zipPath}`);
console.log(`✅ SHA256: ${hash}`);
